keyboard/gamepad入力統一したい
youriko-fanclub/dx4siv3d pull request #2
Opened 2020-10-25 11:17 UTC by direct1889

2020-10-25 14:08 UTC, direct1889 commented on input/gamepad/key/KeyMapping.cpp
> +        }
KeyMappingクラスにボタンとキーの対応を集約
できればファイル読み込みにしてキーコンフィグ入れたい

2020-10-25 14:09 UTC, direct1889 commented on input/gamepad/legacy/GamePad.hpp
> +#if false
legacy/以下は #if false してます
後で消すので一旦見逃してください

2020-10-27 14:19 UTC, yuta1402 requested changes
とりあえず、InputDemoScene だけ見ました。

指摘箇所まとめ:
- `in()`, `GPButton` といった省略形は避けたい
- `input.buttons.pressed()`と`input.dpad.pressed()`を毎回呼び出すの面倒

2020-10-27 14:19 UTC, yuta1402 commented on input/gamepad/demo/InputDemoScene.cpp
> +    const auto& input = in(m_gpid);
in は接続詞ということもあるし名前変えたほうが良さそう。
素直に PlayerInput でいいのではという気がする。

2020-10-27 14:19 UTC, yuta1402 commented on input/gamepad/demo/InputDemoScene.cpp
> +    if (y) { circleIn.movedBy(Vec2(-2,  0) * m_scale).draw(buttonColor(input.buttons().pressedDuration(GPButton::Y))); }
GPButton は省略系で書かないほうがいい気がする。

理由:
- 補完があるから単語が長い分には特に問題ない
- GamePadID は省略されていないので、統一したい

GPButton を残したいなら、GamePadButton で定義しておいて、using GPButton = GamePadButton するというのでもいいかも。

2020-10-27 14:19 UTC, yuta1402 commented on input/gamepad/demo/InputDemoScene.cpp
> +    if (d) { rectIn.movedBy(Vec2( 0,  2) * m_scale).draw(buttonColor(input.dpad().pressedDuration(GPDPad::Down ))); }
GPDPad については、GPButton のレビューと同様。

2020-10-27 14:19 UTC, yuta1402 commented on input/gamepad/demo/InputDemoScene.cpp
> +    const auto& button = input.buttons().pressed();
入力の状態を調べる度に `input.buttons().pressed()` は辛い。
`input.buttons().pressed()` だとすべてのボタンの中で pressed のものが array として返ってきそうに思える。
`input.buttons().pressedDuration(ボタン名)` と同じように、`input.buttons().pressed(ボタン名)`で良さそう。
それか、`input.button(ボタン名).pressed()` とか。
まだこれといった呼び出し方は思いついてないので、なにかあれば意見ください。

2020-10-27 14:19 UTC, yuta1402 commented on input/gamepad/demo/InputDemoScene.cpp
> +    const auto& dpad = input.dpad().pressed();
入力の状態を調べる度に input.dpad().pressed() は辛い。
(以下略

2020-10-27 15:18 UTC, direct1889 commented on input/gamepad/demo/InputDemoScene.cpp
> +    const auto& input = in(m_gpid);
inは仰る通りですね
如何せん呼び出しが長いのが悩み

2020-10-27 15:20 UTC, direct1889 commented
> 補完があるから単語が長い分には特に問題ない
> 入力の状態を調べる度に input.buttons().pressed() は辛い。

呼び出しの文字数が長いのは問題ないけどチェーンが長いのが気になる感じ?

2020-10-27 15:45 UTC, direct1889 commented on input/gamepad/demo/InputDemoScene.cpp
> +    const auto& button = input.buttons().pressed();
色々合って断念したんだけど、どう考えてもbuttonの指定がpressed()より後っておかしいよな...(自問自答)
治します

2020-10-27 15:54 UTC, direct1889 commented on input/gamepad/demo/InputDemoScene.cpp
> +    if (y) { circleIn.movedBy(Vec2(-2,  0) * m_scale).draw(buttonColor(input.buttons().pressedDuration(GPButton::Y))); }
なるほど。統一に関しては確かに仰る通り...
補完があるから〜に関しては確かにそうだし自分も普段は略さない派だけど、inputみたいにあまりにもそこら中で出てくるやつは略すか迷う派です
コード量が減る(行が短く済む)メリットが大きくなるのと、頻出すぎて全メンバー忘れようがないのでなんの略だったかわからなくなるデメリットが薄そう、という理由から。
とりあえず治します

2020-10-27 15:56 UTC, direct1889 commented on input/gamepad/demo/InputDemoScene.cpp
> +    if (d) { rectIn.movedBy(Vec2( 0,  2) * m_scale).draw(buttonColor(input.dpad().pressedDuration(GPDPad::Down ))); }
治しますー
しかしGamePadDPadってパッと見よくわからんよな...
何で十字ボタンの英訳はDPadなんだ...

2020-10-28 13:02 UTC, yuta1402 commented on input/gamepad/demo/InputDemoScene.cpp
> +    const auto& input = in(m_gpid);
>  如何せん呼び出しが長いのが悩み
毎回 `InputManager::instance()->get(gpid)` はさすがに発狂するw
下のコメントで書いてるけど `Input::get(gpid)` は短くて良さそうだな

2020-10-28 13:12 UTC, yuta1402 commented on input/gamepad/demo/InputDemoScene.cpp
> +    if (d) { rectIn.movedBy(Vec2( 0,  2) * m_scale).draw(buttonColor(input.dpad().pressedDuration(GPDPad::Down ))); }
GamePadDPad 意味不明過ぎて笑うww
これは名前変えたほうがいいかもなぁ...。
- DPadButton にする
- GamePadButton に Left, Right, Up, Down を含めてしまう (そういえば DPad と Button 別にしているのってなんでなんだろう:eyes:

DPad は、Directional Pad の略みたいだね。
省略形避けようとは言ったが、じゃあ DPad はいいのかという話もあり、線引が難しいな...

2020-10-28 13:21 UTC, direct1889 commented on input/gamepad/demo/InputDemoScene.cpp
> +    if (d) { rectIn.movedBy(Vec2( 0,  2) * m_scale).draw(buttonColor(input.dpad().pressedDuration(GPDPad::Down ))); }
DPad、確かにDirectionalPadの略だけど、現実世界で呼ばれている通称なので流石に良い気がする
略すのが良くない主要因は他の人が見て意味がわかんないからですし

> 英語圏ではdirectional pad（方向パッド）を略してD-pad（Dパッド）や、control pad（コントロール・パッド）と呼ばれる。

2020-10-28 13:24 UTC, yuta1402 commented
チェーンが長いのは特に気にならないよー

>  入力の状態を調べる度に input.buttons().pressed() は辛い。

どちらかというと pressed() の後にボタン指定が来ることに違和感があて、それがなくなればこの問題は解消すると思われるので、この発言はあまり気にせずで大丈夫!

その 4 つの中だと、
1. `Input::get(gpid).buttons().a().pressed()`
1. `Input::get(gpid).buttons(GamePadButton::A).pressed()`

あたりが良さそう : )

2020-10-28 13:26 UTC, yuta1402 commented on input/gamepad/demo/InputDemoScene.cpp
> +    if (d) { rectIn.movedBy(Vec2( 0,  2) * m_scale).draw(buttonColor(input.dpad().pressedDuration(GPDPad::Down ))); }
たしかに!!
では、DPad みたいなよく使われる省略単語はそのまま使う方向で行きましょう!

2020-10-28 13:35 UTC, direct1889 commented
自分も1/2派だったので良かった
2が基本で、長いから1も用意する感じにします(、というか元々そのつもりでつくってた)
Keyでやり取りするより早いうちにboolにしちゃったほうが複数デバイス扱うのがスッキリしそうだったから途中で今の形式に変えたんだけどやっぱりだめでしたね...という言い訳

2020-10-31 11:37 UTC, direct1889 commented on input/gamepad/demo/GamePadDemo.cpp
> +               x = input.buttons().x().pressed(),
3パターン用意しました
外からだと`Input::get()`の前に`dx::di::`が付くのでもうちょい長くなる

2020-10-31 13:32 UTC, merged