Physics01、TOML
youriko-fanclub/dx4siv3d pull request #4
Opened 2020-11-01 17:02 UTC by direct1889

2020-11-02 03:16 UTC, direct1889 commented on application/AssetManager.cpp
> +    s3d::TextureAsset::Register(desc.key, FilePath::asset_texture + desc.path + textureExtension);
各種ファイルパスをdx::app::FilePathに集約

2020-11-02 03:16 UTC, direct1889 commented on application/ExecutiveManager.cpp
> +    cmp::HotReloadManager::instance()->update();
tomlの変更を監視する

2020-11-02 03:17 UTC, direct1889 commented on application/FilePath.cpp
> +s3d::String FilePath::asset_toml    = asset + U"toml/";
.appファイルからの相対パス

2020-11-02 03:18 UTC, direct1889 commented on application/FilePath.hpp
> +    FilePath() = delete; // static class
とりあえずstatic class化

2020-11-02 03:20 UTC, direct1889 commented on component/Enum.hpp
> +inline s3d::String toString(EnumType value) { return U""; }
enumの汎用処理
どの型に対しても関数名同じで衝突させたくないのでtemplateを特殊化させる形式にしてみました

2020-11-02 03:22 UTC, direct1889 commented on component/Misc.hpp
> +bool approximately0(const s3d::Vec2& value);
浮動小数点数の一致判定用

2020-11-02 03:26 UTC, direct1889 commented on component/parameter/HotReloadManager.cpp
> +}
ひとまずホットリロード対象のtomlはKANJI-asset/toml/hot/に置く
HotReloadable(後述)は自身の参照したいファイルをこのManagerに登録
hotディレクトリをこのManagerが監視し、変更があればそのファイルを参照しているHotRelodableに通知する

2020-11-02 03:27 UTC, direct1889 commented on component/parameter/HotReloadableParameters.cpp
> +    // HotReloadManager::instance()->unregistrate(m_filename);
なんかこれ呼ぶとバグる(深夜2時並の感想)

2020-11-02 03:28 UTC, direct1889 commented on component/parameter/HotReloadableParameters.cpp
> +}
この関数使ってないのでたぶん後で消す
(ディレクトリ監視処理はManagerにまとめたため)

2020-11-02 03:29 UTC, direct1889 commented on component/parameter/HotReloadableParameters.cpp
> +}
ログ出力用
セットでelems()も定義しといたけどいらない気もする

2020-11-02 03:30 UTC, direct1889 commented on input/id/PlayerId.cpp
> +namespace denum {
denum以下に移動

2020-11-02 09:43 UTC, yuta1402 requested changes
大きく気になった点としては、以下 3 つです。
- 正確な関数名をつけたい
- `HotReloadManager` が Parameter クラスを生ポで管理している点
-  バグは直してからマージしたいねｗ

2020-11-02 09:43 UTC, yuta1402 commented on component/parameter/HotReloadManager.hpp
> +    void unregistrate(const s3d::String& key);
unregistrate という単語は存在しないみたいなので、
- registrate -> register
- unregistrate -> unregister

にしよう。

2020-11-02 09:43 UTC, yuta1402 commented on component/parameter/HotReloadableParameters.cpp
> +    // HotReloadManager::instance()->unregistrate(m_filename);
さすがにバグ直してからマージしたいｗｗ

2020-11-02 09:43 UTC, yuta1402 commented on component/parameter/HotReloadManager.hpp
> +    void registrate(const s3d::String& key, HotReloadableParameters* params);
今みたいに Parameter クラスから this を呼ぶ形式だと仕方ない気もするけど、生ポ使っているのが気になった。
`std::shared_ptr<T>` を使って生ポ回避するなら、下記の 2 つくらいが選択肢に入るかなぁという感じです。
1. [enable_shared_from_this](https://cpprefjp.github.io/reference/memory/enable_shared_from_this.html) を Parameter クラスに継承させて、コンストラクタから `HotReloadManager::instance()->registrate(m_filename, shared_from_this());` を呼んで登録する。
1. Parameter クラスのインスタンスを`auto hoge = make_shared<T>()` で生成する。
また、その呼び出し元において、`HotReloadManager::Instance()->registrate(m_filename, hoge);` を呼んで登録する。

2020-11-02 10:05 UTC, direct1889 commented on component/Misc.hpp
> +bool approximately0(const s3d::Vec2& value);
UnityのMathfにあるこの役割の関数がApproximatelyなのでそれと揃えて命名してますー
ただ、普通に見たら言葉足らずというのはまあそうかもしれないですね
approximately zeroの方は「およそゼロ」と訳せるからまだいいけど

2020-11-02 10:07 UTC, direct1889 commented on component/parameter/HotReloadManager.hpp
> +    void unregistrate(const s3d::String& key);
registerは予約語なのよね...
unregistrateが存在しないのは仰るとおりです...

2020-11-02 10:08 UTC, direct1889 commented on component/parameter/HotReloadableParameters.cpp
> +    // HotReloadManager::instance()->unregistrate(m_filename);
申し訳ございません...

2020-11-02 10:12 UTC, yuta1402 commented on component/Misc.hpp
> +bool approximately0(const s3d::Vec2& value);
あーなるほど、であれば approximately でもいいかもしれんね。
approximately0 の方は approximatelyZero の表記のほうが好きなんだけど、どっちが良い？？

2020-11-02 10:16 UTC, yuta1402 commented on component/parameter/HotReloadManager.hpp
> +    void unregistrate(const s3d::String& key);
すみませんすみません、register が予約語なの完全に忘れてました orz
他にそれっぽい意味になりそうな単語は、
- subscribe / unsubscribe
- watch / unwatch

とかですかね。

2020-11-02 10:19 UTC, yuta1402 commented
ごめんなさい間違えて最初のレビューコメントを一部消してしまった。
多分そこまで大事なことは言ってないコメントなので大丈夫なはず...

2020-11-02 10:32 UTC, direct1889 commented on component/parameter/HotReloadManager.hpp
> +    void registrate(const s3d::String& key, HotReloadableParameters* params);
sharedにしなかったのはその実装上の問題もあるし、Manager側には所有権を持たせない方針だったからです
バグの箇所直したので一応生ptrの参照先が寿命切れてることはなくはなったけど、生ptr嫌という気持ちはわかります
(今気づいたけど、自分が生ptrに抵抗なくなってきてるの業務のコードのせいっぽい)

やるなら2かなぁ
もしくは後から登録/解除を禁止して、
`shared_ptr<ConcleteParam> Manager::createParams<Type>(bool /*登録するかフラグ*/)`
つくってManagerにインスタンス作ってもらうのもあり。
自分でつくっておいてあれだけどあんまり途中から登録/解除したいっていう場面なさそうなのでこれいいかも。
hotReloadはReleaseビルドでは切るし

2020-11-02 10:35 UTC, direct1889 commented on component/Misc.hpp
> +bool approximately0(const s3d::Vec2& value);
Zeroにします!

2020-11-02 10:40 UTC, direct1889 commented on component/parameter/HotReloadableParameters.cpp
> +    // HotReloadManager::instance()->unregistrate(m_filename);
直しました!

2020-11-02 10:41 UTC, yuta1402 commented on component/parameter/HotReloadManager.hpp
> +    void registrate(const s3d::String& key, HotReloadableParameters* params);
>  shared_ptr<ConcleteParam> Manager::createParams<Type>(bool /*登録するかフラグ*/)

うん、これで行こうｗ

2020-11-02 10:42 UTC, yuta1402 commented on component/parameter/HotReloadableParameters.cpp
> +    // HotReloadManager::instance()->unregistrate(m_filename);
神

2020-11-02 10:42 UTC, direct1889 commented on component/parameter/HotReloadManager.hpp
> +    void unregistrate(const s3d::String& key);
registerくん存在感ゼロだからな笑 volatileより地味なレベル

2020-11-02 10:43 UTC, direct1889 commented on component/parameter/HotReloadManager.hpp
> +    void registrate(const s3d::String& key, HotReloadableParameters* params);
すべて解決!

2020-11-02 10:44 UTC, yuta1402 commented on component/Misc.hpp
> +bool approximately0(const s3d::Vec2& value);
あざあざ！！

2020-11-02 10:46 UTC, yuta1402 commented on component/parameter/HotReloadManager.hpp
> +    void unregistrate(const s3d::String& key);
まじで存在感ないよな笑

しかも非推奨らしいから消してほしいわｗ
https://cpprefjp.github.io/lang/cpp11/deprecation_of_the_register_keyword.html

2020-11-02 13:57 UTC, direct1889 commented on component/parameter/HotReloadManager.hpp
> +    void registrate(const s3d::String& key, HotReloadableParameters* params);
すべて解決とか書いたけど、よく考えたらParamのインスタンスが消えるときには解除処理必要だった...
subscribe/unsubscribeにします

2020-11-03 00:41 UTC, yuta1402 requested changes
レビューした箇所を修正すればマージ OK です。

2020-11-03 00:41 UTC, yuta1402 commented on component/parameter/HotReloadManager.hpp
> +    static std::shared_ptr<ConcleteParams> createParams(bool withSubscribe = true) {
Conclete 👎 
Concrete 👍

2020-11-03 00:41 UTC, yuta1402 commented on component/parameter/HotReloadableParameters.cpp
> +}
今回の PR で消すなら消し忘れにご注意を。

2020-11-03 01:24 UTC, direct1889 commented on component/parameter/HotReloadManager.hpp
> +    static std::shared_ptr<ConcleteParams> createParams(bool withSubscribe = true) {
あー、自分が一番したくないミスをしてしまった...

2020-11-03 01:41 UTC, direct1889 commented on component/parameter/HotReloadManager.hpp
> +    static std::shared_ptr<ConcleteParams> createParams(bool withSubscribe = true) {
反応が早い笑

2020-11-03 01:45 UTC, direct1889 commented
指摘箇所2点修正+HotReloadManagerにパス指定ミスが有ったので修正
マージします〜

2020-11-03 01:45 UTC, merged